# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('studied', models.CharField(choices=[('BACHELORS', 'Bachelors'), ('ENGINEERING', 'Engineering'), ('INTERMEDIATE', 'Intermediate'), ('SSC', 'SSC')], max_length=200)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
