# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180119_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
