# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180119_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default='college', max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.CharField(default='Computers', max_length=150),
        ),
    ]
