# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20180119_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studied',
            field=models.CharField(choices=[('Bachelors', 'BACHELORS'), ('Engineering', 'ENGINEERING'), ('Intermediate', 'INTERMEDIATE'), ('SSC', 'SSC')], max_length=200),
        ),
    ]
